package com.isaiahnoelpulidosalazar.inpsAndroid;

import org.junit.Test;
import static org.junit.Assert.*;

import java.util.Date;

// Generated by Google AI Gemini 3.5 Flash
public class LocalUnitTest {

    @Test
    public void testCheckEmailSplitMode() {
        Check.Email.shouldUseFullDomain(false);
        Check.Email.addValidDomainName("gmail");
        Check.Email.addValidDomainExtension("com");

        assertTrue(Check.Email.isValid("user@gmail.com"));
        assertFalse(Check.Email.isValid("user@gmail.org"));
        assertFalse(Check.Email.isValid("user@yahoo.com"));
        assertFalse(Check.Email.isValid("invalid-email"));
        assertFalse(Check.Email.isValid("@gmail.com"));
        assertFalse(Check.Email.isValid("user@"));
    }

    @Test
    public void testCheckEmailFullDomainMode() {
        Check.Email.shouldUseFullDomain(true);
        Check.Email.addValidDomain("yahoo.com");

        assertTrue(Check.Email.isValid("user@yahoo.com"));
        assertFalse(Check.Email.isValid("user@gmail.com"));
    }

    @Test
    public void testCheckStringHelpers() {
        assertTrue(Check.hasSymbols("hello@world"));
        assertFalse(Check.hasSymbols("helloworld123"));

        assertTrue(Check.hasNumbers("room 101"));
        assertFalse(Check.hasNumbers("room one"));

        assertTrue(Check.hasSpaces("hello world"));
        assertFalse(Check.hasSpaces("helloworld"));

        assertFalse(Check.hasSymbols(null));
        assertFalse(Check.hasNumbers(""));
        assertFalse(Check.hasSpaces(null));
    }

    @Test
    public void testCheckTimeCalculations() {
        Date now = new Date(1000000);
        Date until = new Date(2000000);

        assertEquals(1000.0, Check.howManySecondsLeft(now, until), 0.001);
        assertEquals(1000.0 / 60.0, Check.howManyMinutesLeft(now, until), 0.001);
        assertEquals(1000.0 / 3600.0, Check.howManyHoursLeft(now, until), 0.001);
        assertEquals(1000.0 / 86400000.0 * 1000.0, Check.howManyDaysLeft(now, until), 0.001);

        assertEquals(0.0, Check.howManySecondsLeft(null, until), 0.001);
    }

    @Test
    public void testCipherCiphers() {
        assertEquals("HLOEL", Cipher.transpositionCipher("HELLO"));
        assertEquals("HLOEL", Cipher.transpositionCipher("HE L LO"));

        assertEquals("DEF", Cipher.caesarCipher("ABC", 3));
        assertEquals("DEF", Cipher.caesarCipher("abc", 3));
        assertEquals("A B C", Cipher.caesarCipher("x y z", 3));

        assertEquals("FBJJN", Cipher.keywordCipher("HELLO", "KEY"));

        assertEquals("CYHHL", Cipher.giovanniCipher("HELLO", "KEY", "C"));
    }

    @Test
    public void testConvertBasic() {
        assertEquals("John", Convert.toRealName("john"));
        assertEquals("A", Convert.toRealName("a"));

        assertEquals(123, Convert.toInt("123"));
        assertEquals(0, Convert.toInt("invalid"));

        assertEquals(1.23f, Convert.toFloat("1.23"), 0.001f);
        assertEquals(0.0f, Convert.toFloat("invalid"), 0.001f);

        assertEquals(1.2345, Convert.toDouble("1.2345"), 0.0001);
        assertEquals(0.0, Convert.toDouble("invalid"), 0.0001);

        assertEquals("null", Convert.toString(null));
        assertEquals("123", Convert.toString(123));
    }

    @Test
    public void testConvertDates() {
        Date date = new Date(126, 4, 4);
        assertEquals("5/4/2026", Convert.dateToMMDDYY(date));
        assertEquals("4/5/2026", Convert.dateToDDMMYY(date));
        assertEquals("2026/5/4", Convert.dateToYYMMDD(date));
    }

    @Test
    public void testMemoryContainer() {
        Memory<String> memory = new Memory<>();
        assertEquals(0, memory.count());

        memory.add("A");
        memory.add("B");
        memory.add("C");
        assertEquals(3, memory.count());
        assertTrue(memory.contains("B"));
        assertFalse(memory.contains("D"));

        assertEquals("A", memory.get(0));
        assertEquals("B", memory.get(1));

        memory.remove("B");
        assertEquals(2, memory.count());
        assertFalse(memory.contains("B"));
        assertEquals("C", memory.get(1));

        memory.removeAt(0);
        assertEquals(1, memory.count());
        assertEquals("C", memory.get(0));

        memory.clear();
        assertEquals(0, memory.count());
    }

    @Test
    public void testSortAlgorithms() {
        int[] unsorted = {5, 1, 4, 2, 8, -2, 0, 4};
        int[] expected = {-2, 0, 1, 2, 4, 4, 5, 8};

        assertArrayEquals(expected, Sort.bubbleSort(unsorted.clone()));
        assertArrayEquals(expected, Sort.cocktailShakerSort(unsorted.clone()));
        assertArrayEquals(expected, Sort.oddEvenSort(unsorted.clone()));
        assertArrayEquals(expected, Sort.selectionSort(unsorted.clone()));
        assertArrayEquals(expected, Sort.insertionSort(unsorted.clone()));
        assertArrayEquals(expected, Sort.shellsort(unsorted.clone()));
        assertArrayEquals(expected, Sort.quicksort(unsorted.clone()));
        assertArrayEquals(expected, Sort.mergeSort(unsorted.clone()));
        assertArrayEquals(expected, Sort.heapsort(unsorted.clone()));
        assertArrayEquals(expected, Sort.introsort(unsorted.clone()));
        assertArrayEquals(expected, Sort.timsort(unsorted.clone()));
        assertArrayEquals(expected, Sort.pigeonholeSort(unsorted.clone()));
        assertArrayEquals(expected, Sort.treeSort(unsorted.clone()));
        assertArrayEquals(expected, Sort.patienceSorting(unsorted.clone()));

        int[] unsortedPositives = {5, 1, 4, 2, 8, 0, 4};
        int[] expectedPositives = {0, 1, 2, 4, 4, 5, 8};
        assertArrayEquals(expectedPositives, Sort.countingSort(unsortedPositives.clone()));
        assertArrayEquals(expectedPositives, Sort.beadSort(unsortedPositives.clone()));

        double[] unsortedDoubles = {0.5, 0.1, 0.4, 0.2, 0.8, 0.0, 0.4};
        double[] expectedDoubles = {0.0, 0.1, 0.2, 0.4, 0.4, 0.5, 0.8};
        assertArrayEquals(expectedDoubles, Sort.bucketSortUniform(unsortedDoubles.clone()), 0.0001);
    }

    @Test
    public void testSortEdgeCasesAndExceptions() {
        assertNull(Sort.quicksort(null));
        assertArrayEquals(new int[]{}, Sort.quicksort(new int[]{}));
        assertArrayEquals(new int[]{42}, Sort.quicksort(new int[]{42}));

        try {
            Sort.countingSort(new int[]{-1, 2, 3});
            fail("Expected IllegalArgumentException for negative elements in countingSort");
        } catch (IllegalArgumentException e) {
            // Test passed
        }

        try {
            Sort.countingSort(new int[]{10_000_001});
            fail("Expected IllegalArgumentException for excessively large elements in countingSort");
        } catch (IllegalArgumentException e) {
            // Test passed
        }

        try {
            Sort.beadSort(new int[]{-5, 2, 3});
            fail("Expected IllegalArgumentException for negative elements in beadSort");
        } catch (IllegalArgumentException e) {
            // Test passed
        }

        try {
            Sort.bucketSortUniform(new double[]{-0.1, 0.5});
            fail("Expected IllegalArgumentException for elements < 0.0 in bucketSortUniform");
        } catch (IllegalArgumentException e) {
            // Test passed
        }

        try {
            Sort.bucketSortUniform(new double[]{1.0, 0.5});
            fail("Expected IllegalArgumentException for elements >= 1.0 in bucketSortUniform");
        } catch (IllegalArgumentException e) {
            // Test passed
        }

        try {
            Sort.pigeonholeSort(new int[]{1, 10_000_002});
            fail("Expected IllegalArgumentException for excessively large range in pigeonholeSort");
        } catch (IllegalArgumentException e) {
            // Test passed
        }
    }

    @Test
    public void testBogoSort() {
        int[] unsorted = {2, 1, 3};
        int[] expected = {1, 2, 3};
        assertArrayEquals(expected, Sort.bogoSort(unsorted));
    }
}